spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # datasourceMysql:
  #  url: jdbc:mysql://localhost:3306/superlig_db
  #  username: root
  #  password: 180200
  #  driverClassName: com.mysql.jdbc.Driver
  # datasource:
  #  url: jdbc:postgresql://localhost:5432/trabzon_db
  #  username: postgres
  #  password: 180200
  #  driverClassName: org.postgresql.Driver
jpa:
  #show-sql: true
  hibernate:
    ddl-auto: validate # validate # Hibernate ddl auto (create, create-drop, validate, update)
  properties:
    hibernate:
      order_by.default_null_ordering: last
      jdbc:
        lob:
          non_contextual_creation: true
      # format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      # log: DEBUG
server:
  error:
    include-message: always